instrumentation:
  include-all-sources: true
  excludes:
  - public/assets/js/vendor/*
  - public/tests/generated/*
  - public/tests/vendor/*
reporting:
  print: summary
  reports:
  - lcov
  - html
  - text
