language: node_js
node_js:
- node
- '4.2'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  apt:
    packages:
    - google-chrome-stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- export PATH=$PWD/node_modules/phantomjs-prebuilt/lib/phantom/bin:$PATH
- npm install -g npm@^5.0.1
script:
- "./go setup"
env:
  matrix:
    secure: eviVtG6s0OtE+iadzDWkEGvwg3RArqnZw6abQjV9bT8hjWkSbO8GFAFMERc15I84gXhL0A3gIVqvu9LiosMqttyMCY81G/cjvW+5trO2vL6WlXS3aHClWo+8YNy+p2KZ0kIvdDwooxxNp1e5/NusTkQbZUlfVSMGB76bUpnxsaWOkdII4FfmvVJXZ1K3/t6/w4TdPE2FmF0gampDfVHXbxbfx7BzdQLu/HtRjgdA5/5fUYtczZYf0BgFs937S5ywvuXi6gy6j9sqHhHoJTNhRbjhqDguADPwtypWXqlyUS2mUMxQWch0WEt8BH5fNmjoYMfRP391p9HBDFDksCkU1wjf0F5jGDEy5/t7pS53NRpcLmOivbpuN8bOyLCYQx+DTXC+uCKCee1yuNONUbyNO7cmiWLPiBuA/HxsPwToR21tx+zyJn7ZshDoX96AHxMB0fONFILRKtVttShkwVNLhRgoNO9+U3RGJp0ufOvxb6ii9JmVIj6uY/siE4QWmiWjo/qG7ErqJW1WknD+MIQ0u2YZd/uTOc+nqNBt+mefArIe2OzXzMS4+TV8ggYqt8+diMYROpLqVoHLQwWDJDP374KixrkZaZguidSZDajq5s0u0u03NHmyrLGZEY4er2qLpe/KreMXqXfPE+O8C7G8yNEL54teiZd7Ao+Vhmeshwk=
