language: node_js
node_js:
- node
- '6'
dist: trusty
sudo: false
cache:
  directories:
  - node_modules
addons:
  chrome: stable
before_install:
- export PATH=$PWD/node_modules/phantomjs-prebuilt/lib/phantom/bin:$PATH
- if [[ ( "$TRAVIS_PULL_REQUEST" != 'false' || "$TRAVIS_BRANCH" == 'master' ) && "$TRAVIS_JOB_NUMBER" =~ [.]1$ ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; chmod +x ./cc-test-reporter; fi
script:
- "./go setup"
env:
  global:
  - secure: nqpv3MQGMDVSIx0TD6CL0oJVAvgD8HyUn02mzJ79HX8DMvT7UGaL6HuXbc7nATX04px9jdbkH2IKIFDuvIc73ZxZFRygwgU1MA+kuAPcafXQKjOwXTyDgTYWMetPM+PFcALY2756MNfeSWTrjOuxq5wuLxHlq1D4CnPvxonKAOmta0qXk69De4+BgDvqC8HDvXGwcWDXjvGOabAAp2Yqi/gU69AZfPm8J9AzkNEqzwOcTCIFihD89drJM85AT0MsnMMFu2r7xktiOoIh2AEkKVIRKsm10q5sKGPPkfj4gCTGTXUZq2732id8lMWv8a1br9S5pLZhJl2L15S6CMS70AthReUW3dTrqiMLhzxirUyblpBvfe56gUkCAzm8IZKEIVXExXZdv3aWzJ2S7YPLd5+HCWthMw5Ahy8zrtu9vY18ByJ1wDgW8EgOaF0LF5683zfbp/dZ0J7gsP19s64oy9va5fdhqXAUdrENpzIgJKCHEc6TLC5gE+0hLiMGaN++XeHgV4uwgPEpqa+TV3OKr5oS1LrtKbhD/4S4zw61toN3wwVKE6h8/w9mVUSkUmmtL9pl1Nax7/54cI2uhD6Vd8chuOKsxs954isk4Aqt4O24db5EOcYxXz2A6xozv0pNweOj200StsV9xH9Ly68LpbXkskq70XHFrsCDu2Q7KIo=
