version: '3'
services:
  custom-links:
    build: .
    ports:
    - "3000:3000"
    environment:
    - CUSTOM_LINKS_REDIS_HOST=redis
    env_file:
    - variables.env
    depends_on:
    - redis
    volumes:
    - ./test-config.json:/etc/custom-links.conf

  redis:
    image: redis:4.0.2-alpine
    expose:
    - "6379"
    volumes:
    - .:/data
    entrypoint:
    - redis-server
    - --appendonly
    - "yes"
