#! /usr/local/env bash
#
# Runs a local url-pointers server
#
# Usage:
#   {{go}} {{cmd}} [<config-file>]
#
# Where:
#   <config-file>  url-pointers configuration file
#
# There must be a redis-server already running.

urlp.serve_tab_completion() {
  local word_index="$1"
  shift
  local args=("$@")
  local word="${args[$word_index]}"

  if [[ "$word_index" -eq '0' ]]; then
    @go.compgen -f -- "$word"
  fi
}

urlp.serve() {
  local server_config="${1:-$_GO_ROOTDIR/test-config.json}"

  case "$1" in
  --complete)
    # Tab completions
    shift
    urlp.serve_tab_completion "$@"
    return
    ;;
  esac

  node "$_GO_ROOTDIR/index.js" "$server_config"
}

urlp.serve "$@"
